language: node_js
node_js: "10"
before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d
  - openssl aes-256-cbc -K $encrypted_5dc437871297_key -iv $encrypted_5dc437871297_iv -in virgil-demo-10380-8d7e72b52304.json.enc -out ./functions/virgil-demo-10380-8d7e72b52304.json -d
  - openssl aes-256-cbc -K $encrypted_15f579b32869_key -iv $encrypted_15f579b32869_iv -in test.config.json.enc -out ./functions/test/test.config.json -d
  - cd functions
install:
  - npm install
script:
  - npm run build
  - npm run test
